### ISSUE TITLE
Improve loading sequence for audio

### ISSUE THREAD

**Issue by samreid** [phetsims/tambo#100]
From https://github.com/phetsims/density/issues/13#issuecomment-608035965

> @samreid is going to take on unifying images, textures, phetioEngine, and brand with a time frame of about 2 weeks, and then pass it off to @jbphet to investigate the sound aspect.

In https://github.com/phetsims/joist/issues/621, @zepumph and I generalized SimLauncher to support more general locks.  

We thought it would be best if sound worked the same way as images, where they are loaded into memory during the startup sequence, before SimLauncher kicks off the sim-specific code.   Maybe this will simplify code in tambo, if it can assume sounds were all preloaded?

**Comment by jbphet** [comment]
> Maybe this will simplify code in tambo, if it can assume sounds were all preloaded?

Yes, it will allow some simplification if we can assume that all sounds are fully decoded before the sim is started.  I'll investigate.

**Comment by jbphet** [comment]
@samreid - I was just doing some investigation on this issue, and I have a question.  The sound library - specifically the file `soundInfoDecoder.js` - works with sound specifications that are either URLs to a sound file (such as an MP3 file) or previously encoded base64 data.  When we made the transition to ES6 modules a few months back, it became necessary to use "grunt modulify" to turn sound files into JS files before they could be used in the code.  It looks like this change made it so that we no longer use URLs at all for sound files, even when running a sim in unbuilt mode.  Am I correct on this?

**Comment by samreid** [comment]
Yes, as I understand, we only use the `grunt modulify` style of audio files at the moment.

**Comment by jbphet** [comment]
This involved a bit more complexity than initially expected because the locks don't block other module loading, they block construction and running of the sim.  Since some sounds can be constructed during module load time, and since there may need to do some examination of the sound data at this time (for instance to trim silence from the start and end), we needed a mechanism to signal when the load actually completed.  I used a `TinyProperty` instance for this and wrapped it with the audio buffer into an object.  This idea was reviewed with both @jonathanolson and @samreid while I was working on it.

Assigning to @samreid for review.  A general review would be good, and I have a couple of specific questions:
- [ ] I ended up creating a module called `base64SoundToByteArray` to do some of the conversion steps for a sound module.  Does this seem like a reasonable approach?
- [ ] I put `base64SoundToByteArray` in chipper since it is part of the load/build process, but I considered putting it in tambo since it was sound-related.  Is there a strong reason to move it to tambo?
- [ ] A new type called `WrappedAudioBuffer` ended up in chipper also, but perhaps should be in tambo.  Any opinion?

**Comment by samreid** [comment]
Generally this looks like a good direction, and I think it is set up well.  I have a question or two and some brainstorming about possible improvements.

Q: In soundManager.js, `reverbImpulseResponse` access is used only in `initialize` which is called in the Sim constructor which is after SimLauncher has loaded everything.  So in that case the link/unlink seem unnecessary.  Does that sound right to you?  Or was this done defensively in case this sound is used statically?  Are there other cases that can be simplified where we know things are used during the startup sequence?

Brainstorming possible improvements:
1. Instead of WrappedAudioBuffer containing a null/non-null AudioBuffer in addition to a true/false TinyProperty, it could have `audioBufferProperty` which starts as null and when it takes its value that means the audio has been decoded.
2. We could add an assertion in WrappedAudioBuffer to make sure the audio is set only once.
3. If we go ahead with a simplification like (1) then we could take one step further and eliminate WrappedAudioBuffer and instead have the module return a `TinyProperty<AudioBuffer|null>`.  That may be simpler but we would lose having a nice place to document things--I'm not sure which is preferable.

In response to the questions:

>  I ended up creating a module called base64SoundToByteArray to do some of the conversion steps for a sound module. Does this seem like a reasonable approach?

Yes, it looks good.

> I put base64SoundToByteArray in chipper since it is part of the load/build process, but I considered putting it in tambo since it was sound-related. Is there a strong reason to move it to tambo?

I feel like either way is OK but I'd slightly lean toward keeping this in tambo.

> A new type called WrappedAudioBuffer ended up in chipper also, but perhaps should be in tambo. Any opinion?

Let's decide on (3) above first.  If we decide to keep WrappedAudioBuffer, perhaps it makes the most sense to put it in tambo.  

> Since some sounds can be constructed during module load time

It would simplify this implementation to only use the audio buffer data after SimLauncher has completed. Could we enforce that as a constraint on our simulations, or is that too impractical?  Can you show an example or two of where data is used before SimLauncher completes (keeping in mind that it looks like the `reverbImpulseResponse` usage is safe).

**Comment by jbphet** [comment]
> Brainstorming possible improvements...

I quite like all three of these suggestions and will move forward with trying them out.  I'm not too worried about the documentation piece, since the documentation in `modulify.js` should be sufficient for us to do a build.

> It would simplify this implementation to only use the audio buffer data after SimLauncher has completed.  Could we enforce that as a constraint on our simulations, or is that too impractical?

I think this would be impractical, or to put it another way, I think we could do it, but I don't think it would be any simpler than it is now.  The usage case that leads to examination of the audio buffer data prior to SimLauncher completing is when any sound clip is constructed as a constant outside of a constructor (not sure what the correct term is for this...a file constant maybe?).  In that case, the sound clip is constructed and the code in the constructor examines the buffer data to see if any silence needs to be trimmed out of it (see the handling of the `trimSilence` option in `SoundClip`).  I can imagine other similar needs in the future, such as needing to know the total duration of a sound once loaded.

All of the shared UI sounds, which are singletons, construct a sound clip on reset.  For an example, please see `resetAllSoundPlayer`.  There are other examples as well.

> I put base64SoundToByteArray in chipper...

I do think I'll move it to tambo.  It has more dependency on and relationship with the other code that is there, so it feels like marginally better encapsulation.

**Comment by jbphet** [comment]
@samreid and I met via Zoom and discussed [the suggestions he proposed above](https://github.com/phetsims/tambo/issues/100#issuecomment-635080361).  We decided that I should move forward with the simplification of `WrappedAudioBuffer` where there is only one field that is a tiny property that is either `null` or an instance of an `AudioBuffer` and to do away with `loadedProperty`.  We also thought it would be best to move the files from chipper to tambo.   We also decided to keep `WrappedAudioBuffer` and not replace it with just a `TinyProperty`, since this gives us a place for the assertion test as well as a good place for documentation about how the loading of audio data works.

@samreid - over to you for review.  I'm okay to close if you're good with what we have now.

**Comment by samreid** [comment]
Looks great, thanks!  I recommend adding an assert message to:

```js
assert( previousAudioBuffer === null && audioBuffer !== null );
```

I'll do that shortly.  Everything else looks good, thanks!

**Comment by samreid** [comment]
While I was adding that assertion message, it seemed like is should convert `if (assert)` to `assert &&`, as is our convention many other places, so I went ahead and did that too.  I don't think that warrants re-modulifying everything though.  @jbphet any other thoughts before closing?

**Comment by jbphet** [comment]
Sounds good to me, and I agree that it doesn't warrant re-modulifying, since it wouldn't change anything anyway, since the modulified sounds just reference `WrappedAudioBuffer`.  I think we're good here.  Closing.

**Comment by samreid** [comment]
On second thought, I realized if we don't remodulify now then it will creep in gradually as new images/sounds are checked in.  So I think we should do it as a batch.  I'll work on that now.

**Comment by samreid** [comment]
Oops, my mistake, the WrappedAudioBuffer isn't part of modulify.  Closing.
