### ISSUE TITLE
console warning even when sound not enabled: "The AudioContext was not allowed to start. . ."

### ISSUE THREAD

**Issue by zepumph** [phetsims/tambo#115]
Recently, when fuzzing natural selection in phet-io studio, I didn't click in the sim, and got 19 and counting of these warnings:

"The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page."

![image](https://user-images.githubusercontent.com/6856943/87101455-9c36a380-c1fb-11ea-8cb5-bf4d0e4711aa.png)

MultiClip:110:
```js

      // start the playback of the sound
      bufferSource.start( now );
```

@jbphet does it bother you that we are getting all the way to MultiClip trying to play a WebAudio bufferSource even when sound is not enabled, or is this expected? I know nothing about this side of tambo, but feel like it is a bit of a code smell that there is potential for this much (how much? I don't really know) code to be able to run even when sound is not enabled for a sim. 

Let me know what you think, feel free to close.

**Comment by jbphet** [comment]
> @jbphet does it bother you that we are getting all the way to MultiClip trying to play a WebAudio bufferSource even when sound is not enabled, or is this expected?

I would, of course, prefer for this not to happen, but there are a few reasons why I don't think it would be worth the time and effort to make it go away.
1. The message only occurs during fuzz testing, and that's because there has been no actual user interaction, so these messages are not something our users will see even with the console open, and we developers also don't see them very much.
2. I think the warning will go away eventually.  Chrome added this message when they implemented the autoplay policy that prevents a web page from producing sound before the user interacts with it, and they wanted to make sure all the developers were aware of it.  Once the world is used to the idea that this is how it works, I think the message will be removed.
3. One way to prevent this message would be to add `if (phetAudioContext.state === 'running' )` all over the place, but that seems ugly and unnecessary to me
4. Another way to prevent this would be to bring back the stubbed audio context (used until recently to fake out the `AudioContext` API so that our code would run on IE) and use that during fuzz tests.  I don't like that option, though, because I sometimes fuzz test tambo by loading a sim with the `fuzz` param and then clicking on it right away, thus enabling sound.

So, those are my thoughts on the matter. @zepumph - if you think something should be done, or if the behavior should be given more consideration, please mark for dev meeting.  If you're cool with my justification for leaving as is, feel free to close.

**Comment by zepumph** [comment]
Thanks for taking to time to explain this to me. I appreciate it.
