### ISSUE TITLE
SoundGenerator behaves differently depending on how output level is initialized

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tambo#128]
@jbphet asked me to create this issue, something I encountered when writing FourierSoundGenerator.js.

These 2 examples behave differently.

This example works as expected.  You'll hear a 400Hz tone with output level 1.

```js
const oscillatorSoundGenerator = new OscillatorSoundGenerator( {
  initialFrequency: 400
  initialOutputLevel: 1
} );
```

This example does not work as expected. You'll hear nothing.

```js
const oscillatorSoundGenerator = new OscillatorSoundGenerator( {
  initialFrequency: 400
  initialOutputLevel: 0
} );
oscillatorSoundGenerator.setOutputValue( 1 );
```

**Comment by jbphet** [comment]
The root of this problem was that the setting of the output level that was occurring during construction hadn't finished by the time the call to `setOutputLevel` happened, so the latter wasn't taking effect.  I've changed the code to cancel scheduled changes on the gain node before setting new ones, and this appears to fix the problem.

To recreate this problem, I added the following code to the bottom of the constructor for `SimLikeComponentsScreenView`.  This turns on an oscillator whenever there is one ball in the chamber on the first screen.  I adjusted the value for `initialOutputLevel` and commented in/out the call to `osg.setOutputLevel( 1 )`.  I was able to duplicate the described behavior, and the problem went away after my changes.

```js
    // TODO: Temporary code for testing output level changes.
    let osg;
    model.numberOfBallsProperty.link( numberOfBalls => {
      if ( numberOfBalls === 1 ){
        osg = new OscillatorSoundGenerator( {
          initialFrequency: 400,
          initialOutputLevel: 0
        } );
        osg.setOutputLevel( 1 );
        soundManager.addSoundGenerator( osg );
        osg.play();
      }
      else if ( osg ){
        osg.stop();
        soundManager.removeSoundGenerator( osg );
        osg = null;
      }
    } );
```

I regression tested this by exercising the tambo demo and testing sound on balloons-and-static-electricity.

@pixelzoom - Please review the change and, if you're so inclined, take it for a test drive to make sure it's fixed.

**Comment by pixelzoom** [comment]
Looks good, seems to be working fine (tested in the context of Fourier).  Closing.
