### ISSUE TITLE
Sound initialization problem with initialScreen query parameter

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tambo#137]
When using the `initialScreen` query parameter, there seems to be a sound initialization problem.  Sound is very faint for the first UI component that I interact with on a screen. Any 'user-interface' category sound seems to have this problem.  After that, output level is fine.  

Perhaps you're relying on some initialization that occurs on the Home screen, and isn't happening because we're starting with a non-Home screen.

I observed this in master with multiple sims (Fourier, Waves Intro,...) on macOS + Chrome.  

I thought that single-screen sims (like Ohm's Law) might have this problem, since they don't have a Home Screen.  But they do not.

**Comment by pixelzoom** [comment]
> I thought that single-screen sims (like Ohm's Law) might have this problem, since they don't have a Home Screen. But they do not.

Ha! If I run Ohm's Law with `?initialScreen=1`, it does have this problem.

**Comment by pixelzoom** [comment]
@jbphet and I spoke about this on Zoom.  He things this is related to this console warning: 

> phetAudioContext.js:14 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
(anonymous) @ phetAudioContext.js:14

If you click anywhere in the browser other than on a UI component, then the first UI component will sound normal output level.  And he's 90% sure there's nothing related to `initialScreen`.  But I observed the same behavior with and without `initialScreen` query parameter.  So @jbphet will have a look to confirm.

**Comment by jbphet** [comment]
@pixelzoom's explanation above is accurate.  This behavior is related to the auto-play policy that was added to all of the browsers that we support over the last few years.  Here are some related issues:

- https://github.com/phetsims/tambo/issues/9
- https://github.com/phetsims/tambo/issues/58
- https://github.com/phetsims/gravity-force-lab/issues/252

This isn't an exhaustive list, since this issue has had a lot of related sub-issues.

As I think about this, it's probably worth having a separate, specific issue in tambo that describes the problem and that is deferred for now.  I'll do that.
