### ISSUE TITLE
Get the duration of a SoundClip

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tambo#141]
As I'm starting to add sound to Fourier, I'm seeing code like this in WaveInteferenceSlider.js:

```
const MIN_INTER_CLICK_TIME = ( 1 / 60 * 1000 ) * 2; // min time between clicking sounds, in milliseconds, empirically determined
```

Setting the time between sounds empirically is brittle.  Can we add a method to get the duration of a SoundClip, based on it's configuration (playback rate, etc.)?

**Comment by jbphet** [comment]
I've added a method for this to `SoundClip`.  The Web Audio `AudioBuffer` type has a duration field (who knew?), so the code uses a combination of that value and the playback rate.  Note that this can only be called after the module load phase, since it has to wait for the buffer to finish being decoded before it can provide a value.  I've added an assert to catch that case if it come up.

@pixelzoom - back to you to try it out and provide any feedback.

**Comment by pixelzoom** [comment]
I immediately ran into a problem.... How do I get the duration of a SoundClipPlayer, for example generalSoftClickSoundPlayer.js?  The SoundClip is private, and there's nothing in the SoundClipPlayer API that provides access to `getDuration`.

**Comment by pixelzoom** [comment]
@jbphet and I discussed on Zoom.  He's thinking of redesigning things so that SoundClipPlayer goes away, there's a global map of audio buffer data (so that data is only loaded once), and clients instantiate SoundClip.

**Comment by pixelzoom** [comment]
@jbphet and I discussed on Zoom.

I tried soundClipPlayer.soundClip.getDuration (which is private) and it worked. But there the duration of generalSoftClickSoundPlayer.js was much longer than expected. @jbphet discovered that it has a long tail that is just about inaudible, so he's going to trim it.

Re getting access to soundClipPlayer.soundClip.getDuration... @jbphet is thinking of redesigning things so that SoundClipPlayer goes away, there's a global map of audio buffer data (so that data is only loaded once), and clients instantiate SoundClip.

**Comment by jbphet** [comment]
This is going to be a bit more difficult to do well than I originally thought.  I already knew that encoding a file as MP3 added some silence to the beginning of the sound, but it looks like it also adds silence to the end, so the duration values being returned are longer than the actual sound.  I'll look into the code that already exists in `SoundClip` for trimming silence next, but I'll have to come back to it and work on other things for a bit.

**Comment by jbphet** [comment]
In a discussion with @pixelzoom today I proposed an alternative for achieving the goal of not playing too many iterations of the same sound clip at once.  Rather than using the duration, we could add a `maxSimultaneousPlaying` parameter to a clip that would prevent it from playing more than a configurable number of the clip such that they overlap.  That information is already tracked in the `SoundClip` class in `this.activeBufferSources.length`.

I'll try this out when working to add generalized sound for sliders in https://github.com/phetsims/sun/issues/697.

**Comment by jbphet** [comment]
I've added a method to `SoundClip` to get the number of playing instances called (perhaps not surprisingly) `getNumberOfPlayingInstances`.  I tried it out for a sound generator in balloons-and-static-electricity and found it worked pretty well.  I started to also add an options value to `SoundClip` to set a max number of playing instances, but part way through the effort I started to have second thoughts.  It doesn't feel great to have an option that could cause the `play` method to not play anything.

@pixelzoom - Would you be okay with just having the `getNumberOfPlayingInstances` method and keeping the onus on the client for limiting the number of simultaneous playing instances?  Do you feel like this would meet the spirit of the original request for getting the duration?

**Comment by pixelzoom** [comment]
Yes, that sounds fine.

**Comment by jbphet** [comment]
Cool, thanks.  I've deleted the `getDuration` method and we can focus on using `getNumberOfPlayingInstances` from here on out.  Closing.

**Comment by samreid** [comment]
There is a TODO referring to this issue, I'm not sure if it needs attention or not, @jbphet can you please advise?

```js
const SNAP_SOUND_DURATION = 25; //TODO generalSoftClickSoundPlayer.duration, https://github.com/phetsims/tambo/issues/141
```

**Comment by jbphet** [comment]
> There is a TODO referring to this issue, I'm not sure if it needs attention or not, @jbphet can you please advise?

This is in fourier-making-waves.  Assigning to @pixelzoom to address.

**Comment by pixelzoom** [comment]
TODO deleted, closing.
