### ISSUE TITLE
Support mutable range in `ValueChangeSoundPlayer`

### ISSUE THREAD

**Issue by zepumph** [phetsims/tambo#184]
In https://github.com/phetsims/area-model-multiplication/issues/9, we want to use a `ValueChangeSoundPlayer` but the potential range can change. It would be great if that could be a Property. I'll prototype something out and then discuss with @jbphet. Let me know if you have objections.

**Comment by zepumph** [comment]
This is working really well over in https://github.com/phetsims/area-model-multiplication/issues/9. @jbphet can you give me a spot check?

**Comment by jbphet** [comment]
Looks reasonable to me.  The only thing I noticed was a comment that says, "No need to dispose. Sound generators do not get disposed" which was subsequently followed by what looks like code to dispose the linkage.  Maybe consider deleting that comment unless I've misunderstood something.  And generally, I don't think we should say "Sound generators do not get disposed" since that isn't necessarily true even though it is often the case.

**Comment by zepumph** [comment]
Ahh shoot, yeah, while I was writing that I was thinking, "this will not pass code review" so I added dispose support. Thanks for catching that. Closing
