### ISSUE TITLE
Address problems related to `ContinuousPropertySoundGenerator.resetInProgressProperty`

### ISSUE THREAD

**Issue by zepumph** [phetsims/tambo#186]
Recommended from a conversation with @pixelzoom over in https://github.com/phetsims/faradays-electromagnetic-lab/issues/77.

This could be internal to ContinuousPropertySoundGenerator, and doesn't need to cascade to individual sim usages (since those are reset specific). I just think it would make the API for the sound generator more usable and general [@pixelzoom: if `resetInProgressProperty` were renamed to `updateEnabledProperty`]. 

@jbphet does this sound reasonable? I'll implement if you'd like. Is that the best new name?

**Comment by pixelzoom** [comment]
I'd also like to see something like this added to common-code, which was done in CAV, and which I intend to do in FEL:

```
// isResettingAllProperty.ts
const isResettingAllProperty = new TinyProperty( false );
faradaysElectromagneticLab.register( 'isResettingAllProperty', isResettingAllProperty );
export default isResettingAllProperty;
```

To be wired into resetAllButton like this:

```ts
  this.resetAllButton = new ResetAllButton( {
      listener: () => {
       isResettingAllProperty.value = true;
       ...
       isResettingAllProperty.value = false;
      },
      tandem: options.tandem.createTandem( 'resetAllButton' )
    } );
```


Then use `isResettingAllProperty` where necessary, instead of having to pass it around through multiple layers of constructors.

This is similar to how PhET-iO's `isSettingPhetioStateProperty`.

**Comment by zepumph** [comment]
Yeah I like that quite a bit. If @jbphet likes it, then I'm happy to implement.

**Comment by pixelzoom** [comment]
Summary of some more discussion that @zepumph and I had in Slack#DM:

* Move ResetAllButton to joist so that it's clear that it's specific to joist and how it's used in ScreenView, and not as generally reusable as other components in scenery-phet
* Also `screenView.interruptSubtreeInput()` into ResetAllButton, which is chronically duplicated (and often omitted) in sim code.

**Comment by jbphet** [comment]
The idea of having a centralized `isResettingAllProperty` seems like a win to me for consistency and avoidance of code duplication.  In that case, I am assuming we would change the current `resetInProgressProperty` option for the above-mentioned sound generator to something like `updateDuringReset`, and have it default to `false`, and then use the globally available Property.

Back to @zepumph, since he said he was up for doing the implementation.

**Comment by pixelzoom** [comment]
> ... In that case, I am assuming we would change the current `resetInProgressProperty` option for the above-mentioned sound generator to something like `updateDuringReset`, 

No, not `updateDuringReset`.  We are trying to decouple this from being specific to "reset".   @zepumph suggested `updateEnabledProperty`, and I'm +1.

**Comment by zepumph** [comment]
Hmm, I'm also curious why we can't use the soundGenerator 'enabledControlProperties' for this case, I'll look into it more.

**Comment by zepumph** [comment]
I had good success with the idea of using enableControlProperties. 

I got particularly excited about it when I saw this precedent: https://github.com/phetsims/tambo/blob/f9fc303fa5433276c76b6041158f77b6ccffb517/js/demo/testing/view/TestingScreenView.ts#L292

As for the pattern more generally, @pixelzoom, I wonder if we want to actually have a singleton that says "resetNOTInProgressProperty" so we can pass it directly into SoundGenerators. Can you please review the above while I go work on https://github.com/phetsims/tambo/issues/187.

**Comment by pixelzoom** [comment]
> I had good success with the idea of using enableControlProperties.

I really do not like this pattern. It differs from the `enabledProperty` pattern used everywhere else. (Can you imagine Node with enableControlProperties?)   If  the logic always needs to be inverted for 1 or more Properties (in addition to the resetNOTInProgressProperty) then you need to create one or more DerivedProperty anyway.  And it complicates the API if we need the option of PhET-iO instrumentation.

> I got particularly excited about it when I saw this precedent:

I wouldn't call that a precedent.  I would call that a bad API that should be replaced ASAP, before it's used further.

So... I think we should stick with the original plan -- `updateEnabledProperty: TReadOnlyProperty<boolean>`.  And if the client needs a derivation that involves > 1 Property (possibly including isResettingAllProperty.ts) then the client should create a DerivedProperty.

**Comment by zepumph** [comment]
If this issue has turned into changing the entire way that tambo controls its enabled, I'm not sure that I agree. Perhaps lets close this issue and conduct a mass refactor over in https://github.com/phetsims/tambo/issues/189, if that is what is deemed appropriate. If we proceed with `updateEnabledProperty`, then we are recognizing that ContinuousPropertySoundGenerator requires a unique and custom solution, which I do not believe it does.

**Comment by pixelzoom** [comment]
Re `isResettingAllProperty`, please see https://github.com/phetsims/tambo/issues/190:

> If we don't want sound when doing a "Reset All", why are we making every generator/clip deal with it? Why are we not handling it globally in soundManager.ts.

**Comment by pixelzoom** [comment]
I'm going to unassign myself.  If I'm going to provided feedback while trying to move FEL sound forward, then PhET needs to allocate resources for common code in some (the next?) iteration.

In the meantime... I'm concerned that we may have some partial work in main which is liable to remain there for a long time before it's completed and vetted.   Since @zepumph commited that work, so I'm going to assign this issue back to him. @zepumph If you feel like this issue is in a safe stopping place, were we can leave it unattended for awhile, then feel free to unassign yourself.  If not, please put main in a "safe" state before unassigning.

**Comment by zepumph** [comment]
Yes thanks. I believe that the next step here is https://github.com/phetsims/tambo/issues/189, which will be done generally. We may also choose to do more work generally for reset-specific sound cases in https://github.com/phetsims/tambo/issues/190. I believe that closing this issue is best. We did good work by removing a custom option and moving it into a general feature of SoundGenerator. Now we just need to improve those general patterns. Please reopen if you'd like anything more done to `ContinuousPropertySoundGenerator`'s reset handling.
