### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by jbphet** [phetsims/tambo#39]
The tambo library is ready for a first round of code review.  The library itself should be reviewed as common code, i.e. code that will be used in all simulations that produce sound, which at some point will likely be all HTML5 sims.

The demo code will not be published as a separate sim, and should be reviewed for its ability to serve as a good example of the usage of the library as well as a decent set of test cases.

The library is currently being used in the John Travoltage simulation, the reviewer is encouraged to look at the usages there and comment on anything that looks problematic or confusing.

There are some known features that will be added over time, and these will be reviewed as added.

**Comment by pixelzoom** [comment]
With John Travoltage, use`&supportsSound&supportsEnhancedSound` and select "Enhanced Sound" from the PhET menu.

**Comment by pixelzoom** [comment]
Code review is complete.  

Overall the abstractions were easy to understand, and this looks like a good approach.  An understanding of Web Audio (and audio in general) is needed to understand and maintain tambo. I didn't need to dive too deep for this review, but that might be because I have an audio engineering background.

Besides the 6 issues that I created (linked above), most of what I did was to put `//REVIEW` comments in the code. Most of those comments are related to documentation, and I'd be happy to discuss any that are unclear or controversial.

Back to @jbphet.

**Comment by jbphet** [comment]
At this point I've addressed all the `// REVIEW` comments and all of the GitHub issues that resulted from the review with the exception of the one about [finishing the ES6 conversion]().  I'm holding off on that one in order to try to get a release out that includes this library, and I'll tackle it in the next couple of weeks.

@pixelzoom - okay to close, or do you want to look through the commits and issues?

**Comment by pixelzoom** [comment]
Took a quick peek, looks good, closing.
