### ISSUE TITLE
how do we determine whether a sound effects library can be used?

### ISSUE THREAD

**Issue by jbphet** [phetsims/tambo#4]
We have a contractor who is doing some work for the sonification effort, and he has a library (and maybe several) that he would like to draw from.  How do we determine whether sounds from a given library can be used?  As we figure this out, I'd like us to keep track of the specific library or libraries in question and log our determination in this GitHub issue.

**Comment by samreid** [comment]
PhET has a number of constraints due to our grants, commercial partners and we need to be able to relicense our products, hence we usually need to have new license types approved by our lawyer.  If the artist that created the sounds can cross-license them to PhET as public domain things get a lot simpler.  As described in https://github.com/phetsims/sherpa/blob/master/third-party-licenses.md#third-party-media most of the 3rd party artwork used by PhET is public domain.

**Comment by emily-phet** [comment]
@ariel-phet and/or @kathy-phet Can you take a look at the license @Ashton-Morris links to here: https://github.com/phetsims/tambo/issues/4#issuecomment-351221789. My interpretation is that this would not be compatible with our use - and we should go ahead and assume that the sounds from these libraries cannot be used - but I'm curious about your thoughts first.

**Comment by ariel-phet** [comment]
I am no lawyer and generally stay out of these questions. My common sense opinion would be that the license above seems quite incompatible.

**Comment by kathy-phet** [comment]
I reviewed it, and agree. Since it does not allow re-licensing, we cannot use sounds made with these libraries.

**Comment by kathy-phet** [comment]
A source like this: https://freesound.org/ has creative commons licensed sounds, but quality is likely variable and not customizable.

**Comment by Ashton-Morris** [comment]
Ok I will source my own material from now on. Thanks for looking into it.

**Comment by jbphet** [comment]
Seems like we've reached a clear conclusion - thanks everyone.  Closing.
