### ISSUE TITLE
enable TamboKeyboardHelpContent by default in demo

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tambo#43]
Related to code review https://github.com/phetsims/tambo/issues/39.

`TamboKeyboardHelpContent` lives in tambo/js/demo/, but isn't enabled in the demo by default.  You need to add the `accessibility` query parameter.   Consider enabling it by default, by passing option `accessibility` to Sim in tambo-main.js, ala john-travoltage-main.js.

**Comment by jbphet** [comment]
I haven't enabled accessibility by default because the primary reason for supporting the `accessibility` option at all in this sim is to have a means to make the keyboard icon appear on the nav bar so that we can see how the layout looks in conjunction with the sound icon.  This sim doesn't really have much in terms of an accessibility implementation - no descriptions or PDOM cusomizations, or anything beyond the default keyboard nav support.  It probably never will have these, since it's for internal use only.  So, my preference is to leave accessibility off by default.

@pixelzoom - if you strongly disagree we can discuss with others, but if you're reasonably okay with this it can be closed.

**Comment by pixelzoom** [comment]
It sounds like the argument is that `TamboKeyboardHelpContent` is insignificant, so it's not worth turning on accessibility by default.  But it does exist, and it's in common code, so enabling accessibility by default would ensure that it's tested by CT.  As is, it's not being tested. And since it's "for internal use only", why not just have it on all the time? That is after all the longterm goal for all PhET runnables.

**Comment by samreid** [comment]
It is easy to add query string combination for CT.  In fact, some tests are run with `&accessibility`, see https://github.com/phetsims/aqua/blob/731d147d29653a9f823e97210b4ba085286406cc/js/continuous-server.js#L668-L676

After reviewing @jbphet and @pixelzoom remarks, I'm inclined to believe that tambo accessibility should be off by default.  This will match with the default of many sims.  Once most sims (or most sonified sims?) have accessibility on by default, then it might make sense to turn on tambo accessibility by default.

**Comment by jbphet** [comment]
Discussed in the 9/20/2018 dev meeting, and we decided to go ahead and turn it on.  Be it known that the a11y implementation in this sim is the default, minimal functionality.

**Comment by jbphet** [comment]
The option has been added to turn a11y on for this demo sim.  Closing.
