### ISSUE TITLE
consistent names for booleans

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tambo#46]
Related to code review https://github.com/phetsims/tambo/issues/39.

Boolean names are a bit inconsistent.  E.g. `SoundClip` has `isPlaying`, while `SoundGenerator` has `locallyEnabledProperty` and `fullyEnabledProperty`.   Should all boolean names have an "is" prefix? That was the message that I got when I worked on https://github.com/phetsims/scenery-phet/issues/388 recently.  On the other hand, we've consistently used `enabledProperty` rather than `isEnabledProperty`. 

This might be a good issue to get input from other developers.

**Comment by samreid** [comment]
Searching for `Property.<Booolean>`, I'm seeing cases like:

```
visibleProperty
solventVisibleProperty
allowExponentsProperty
factorsBoxExpanded
areaBoxExpanded
expandedProperty
isActiveProperty
previousEnabledProperty
nextEnabledProperty
allowCheckingProperty
countingVisibleProperty
showDragHandlesProperty
laserOnProperty
allCollectionBoxesFilledProperty
```

Searching for `{boolean}` I see cases like:
```
isStale
passed
isBuild
animate 
centered
showGridProperty
excludeSign
hasAreaEntry
```

Some of these already have `is` and are very clear.  Some of them, such as `hasAreaEntry` are very clear and should not be changed to have an `is` prefix.  Some are plural like `allCollectionBoxesFilledProperty` which could use `are` instead of `is`.  I think `passed` and `animate` and `centered` are clearer without an `is` prefix.  Some of these such as `nextEnabledProperty` could benefit from an `is` prefix.  Some with `visible` and `enabled` don't seem to need it.  Perhaps we just need to evaluate on a case by case basis?

**Comment by pixelzoom** [comment]
@samreid said:
> Perhaps we just need to evaluate on a case by case basis?

+1.  I don't think we need/want a blanket policy.  But consistency is desirable for things that should have the same name.  E.g. we shouldn't try not to use both `playing` and `isPlaying` in common code.

**Comment by Denz1994** [comment]
An "is" or "has" as a prefix to me sounds like the start of a true or false question, which fits well for boolean types. Regardless of the name of the variable, the type should be referenced to determine if it's a boolean, so I don't have a strong opinion on a naming convention.

**Comment by jbphet** [comment]
Discussed in the 9/20/2018 dev meeting, decided that having a blanket policy is probably not worthwhile, but it would be good to have consistent names for similar concepts in the common code.  For instance, we shouldn't have booleans named both `playing` and `isPlaying` in different places in the common code.  We looked through the common code and didn't see any usages of `playing`.  So, the general policy to developers is to try to be consistent with the same names across common code repos, but to use our own discretion about whether to use prefixes like `is`, `has`, and so forth based on common usage in the English language.  

No further work to be done here, closing.
