### ISSUE TITLE
What shall we retain for sound assets?

### ISSUE THREAD

**Issue by jbphet** [phetsims/tambo#52]
This issue originally came from https://github.com/phetsims/tambo/issues/28#issuecomment-415485395, but has become an issue unto itself.

The basic question is captured in the title, and concerns what we should keep around in terms of assets corresponding to the sounds used in a sim.  Originally, we were thinking that we'd keep the source files in the same way that we keep Adobe Illustrator files for images, but this has proven impractical.  As of this moment, the proposal is to keep an uncompressed .wav file as the asset, describe in the `sounds/license.json` file who created the file, and keep some history in the sound design document.

The main two use cases we want to support with this are:
1. Prove that we created the sound and didn't take it from someone else without permission
2. Create new sounds based on existing ones that we like

**Comment by emily-phet** [comment]
After thinking about this - perhaps the root of the issue lies in the role @Ashton-Morris is playing as designer. PhET as an entity isn't really creating the sounds that have a proprietary component in the source file. The ownership of those proprietary components is by @Ashton-Morris. Perhaps what might be useful is some documentation that @Ashton-Morris created the sounds, he licenses them (the wav file) as CC-BY, and phet is *using* them consistent with a CC-BY license. 

Sounds created that do not have a proprietary component in the source files, e.g., ableton files that MW is putting together, synthesized sounds @jbphet creates/implements, can follow the process proposed in 
https://github.com/phetsims/tambo/issues/52#issue-385014289. In these cases, only the use of basic sound creation software is used, not proprietary sounds or proprietary plug-ins, to create the final - open source - sound.

@jbphet @Ashton-Morris what do you all think of this?

**Comment by kathy-phet** [comment]
@emily-phet and I just discussed this issue. Ashton is working for PhET - either as a contractor or an employee - so it is not necessary or appropriate for him to license the file to us as CC-BY. 

What you have here is fine for documentation: 
  "07_Button_Reset_All_v3-8-kbps-mono.mp3": {
    "text": [
      "Copyright 2002-2018 University of Colorado Boulder"
    ],
    "projectURL": "http://phet.colorado.edu",
    "license": "contact phethelp@colorado.edu",
    "notes": "created by Ashton Morris for PhET"

We do not need the source files as proof for us to own copyright to the sound delivered by Ashton, just as a graphic artist doesn't need to deliver .ai files to us when they deliver an image. It's nice, of course, to have the source files to recreate or tweak things, but I understand that for these sounds that is not practical. 

For other sounds, where source files are available or owned by PhET, then would be great to keep those available and organized for further manipulation.

**Comment by emily-phet** [comment]
Thanks @kathy-phet 
I think some of the confusion stemmed from the fact that we typically have the .ai files for artwork, but your comment:

> We do not need the source files as proof for us to own copyright to the sound delivered by Ashton, just as a graphic artist doesn't need to deliver .ai files to us when they deliver an image. 

addresses that.

**Comment by jbphet** [comment]
Sound like the bottom line is that we keep the original .wav files and we keep the original source files if we can but we don't have to.  In the license file, we'll say who created it, as shown in the comment above.  That should do it, closing.
