### ISSUE TITLE
Static and significant performance issues.

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/tambo#60]
For https://github.com/phetsims/QA/issues/219#event-1953042350
When testing iOS 9 I noticed that a staticy sound would be heard when using the sliders and reset button.  This is also seen on iOS 10.  In addition, iOS 12, and to a lesser extent 10, had significant performance issues.  When using the profiler querry parameter I saw the frame rate on iOS 12 drop as low as 15.  This occurred on the published sim as well, though less drastically.  iOS 10 crashed while using profiler but did not when the querry parameter was off.
iOS 10 sample of the sound: https://drive.google.com/file/d/1B24XqKqq7dLtaPx-HIMGYcXTXf4ROTDz/view?usp=sharing

**Comment by KatieWoe** [comment]
Moving to tambo as I saw this same issue during https://github.com/phetsims/QA/issues/289
Ohm's Law on iOS 12.1.4 iPad Air 2.  I didn't hear the static after letting go of the slider, but the sound doesn't continue for long, so it is hard to tell.

**Comment by KatieWoe** [comment]
Update for Ohm's Law.  I'm hearing a bit of the static on Win 10 chrome

**Comment by KatieWoe** [comment]
Steele Dalton [5:11 PM]
wait are you talking about the ticking sound that's played at every 1.5 V interval?

Kathryn Woessner [5:12 PM]
It also happens with resistance, so I thought it was something else.

Steele Dalton [5:13 PM]
well actually it just happens on every press of an arrow key too. Is that the sound you are talking about?

Kathryn Woessner [5:14 PM]
Sounds like it.

**Comment by phet-steele** [comment]
RE https://github.com/phetsims/tambo/issues/60#issuecomment-464929837, I had stated that this particular sound in OL seemed very intentional. If it isn't.....I vote we keep it 😄

**Comment by jbphet** [comment]
It has been about a year since there was any action on this issue.  @KatieWoe - can you please test on a few of our supported devices and see if the crackling problem still manifests?  I am still of the mind that this is probably a problem with the iOS devices where the touchdrag activities compete with sound generation for resources, but there is a possibility that it's something that we're doing in our code that is causing this or making it worse.  With this in mind, it would be good to know if anything about the situation has changed.

**Comment by KatieWoe** [comment]
Going back and looking at Ohm's Law on a few platforms, I think that instance was intended. I'll keep my eye out though. Note that iOS 9 and 10 have been dropped by this point.

**Comment by jbphet** [comment]
@KatieWoe - I see that you've assigned this back to me, but I'm not yet clear on whether the problem still exists.  From the comment just above, it sort of sounds like something that was heard as a glitch was actually intentional.  So, to be clear, does this problem still exist and, if not, can we close the issue?

**Comment by KatieWoe** [comment]
I don't think it exists, at least on supported platforms that I could see. I'll keep an eye out and reopen if I do see something, but I think it can be closed for now.
