### ISSUE TITLE
Why does soundManager.addSoundGenerator return an id?

### ISSUE THREAD

**Issue by samreid** [phetsims/tambo#63]
`soundManager.addSoundGenerator` has:

> `@returns {string|null} - unique ID of sound generator, null if add not allowed `

But none of the 73 occurrences use it, and the documentation doesn't indicate what it might be used for.  Should it be removed?

**Comment by jbphet** [comment]
At the time it was initially created, I thought it might be useful to have a "handle" that could be used to remove a sound generator when it was no longer needed.  That need hasn't arisen yet, so I'm happy to remove it.

@samreid - I'm thinking we modify the method to return a boolean that indicates whether the add was successful or not.  The failure conditions would be if the soundManager wasn't initialized or if the sound generator was already present.  We could also just return nothing, and just assert in these two situations.  Now that I write it down, I think the latter would be simpler for the clients.  What's your opinion?

Also, I'm not likely to make this change until after the Ohm's Law release that is in progress is created in order to make sure we don't mess anything up with the sound.

**Comment by samreid** [comment]
Assertions sound appropriate for this case.

**Comment by jbphet** [comment]
I've removed the ID, and tested by running the tambo demo through its paces and then fuzz testing it.  I also spot checked sound on John Travoltage, Resistance in a Wire, and Ohm's Law and everything sounded good.  I'm just going to close this issue, but @samreid - feel free to review if you see this go by and you feel the need to take a look.
