### ISSUE TITLE
Should soundManager be allowed to play sounds before the sim is started?

### ISSUE THREAD

**Issue by samreid** [phetsims/tambo#64]
Inspired by https://github.com/phetsims/wave-interference/issues/381, I noticed that soundManager can play sounds while the splash screen is still showing.  Should we add logic to tambo to suppress sounds until the sim is shown?

**Comment by jbphet** [comment]
Nice find, i.e. that clicking the splash screen can create a sound.  We might be able to add some logic to soundManager to prevent this, but there are some browser differences around the way gain nodes work, so code to address this might not work in all cases.  I logged some issues about this with the Web Audio API group, see https://github.com/WebAudio/web-audio-api/issues/1842 (this got split into some other issues, so you'll have to follow through the chain if you're really interested).

@samreid - is there any sort of a "sim load complete" emitter that the sound manager could watch for?  If so, and if you think it's worthwhile, we could set the value of the sound manager's master gain node to zero until initialization completes, then turn it up when the "sim loaded" (or whatever it's called) event occurs.  That would prevent the issue on at least some platforms.

Alternatively, we could record a sound clip that says, "Relax, I'm almost ready" and just play that if the user tries to interact with the load screen. ;-)

**Comment by samreid** [comment]
> @samreid - is there any sort of a "sim load complete" emitter that the sound manager could watch for? 

`Sim.endedSimConstructionEmitter` seems appropriate.

**Comment by jbphet** [comment]
In https://github.com/phetsims/tambo/commit/515673bb596f0413390a455b73ae2f5f7e66d570 I modified the `soundManager` to disallow sound production until the sim initialization is complete by using the emitter the @samreid recommended above.  I tested this by logging the gain value, and I can see that it is zero initially and changes to 1 when initialization completes.  I have two questions about this for you @samreid:

+ I hooked up to the emitter in the initialization routine because it didn't seem to exist during construction of the soundManager.  This works fine now, but are we confident that `soundManager.initialize` will always be called before this emitter fires?
+ I didn't instrument `simInitializedProperty` for phet-io since it is purely internal and I don't think external users should ever manipulate it or would want to monitor it, at least not in this context.  Is this the right call and is this okay to do in phet-io world?

**Comment by samreid** [comment]
Review blocks publication for any sims with sound.

**Comment by samreid** [comment]
I confirmed this fix works properly, thanks!  I have a few recommendations for improvements:

- [ ] Can the `simInitializedProperty` be converted to a local `const` since it doesn't seem necessary to be stored on the soundManager?
- [ ] Right now it works because the startup sequence (a) creates the soundManager then (b) triggers the Sim emitter.  If the code changed in the future so that the `soundManager` was created after that emitter fired, we would have no way of knowing, and sound would never be generated.  Should we convert this Sim emitter to a `Property` so it can be checked at any time?  That could also lead to easier usage in `soundManager`.

**Comment by jbphet** [comment]
> Can the simInitializedProperty be converted to a local const since it doesn't seem necessary to be stored on the soundManager?

Yes, good catch.  I was thinking it had to be a property in order to work with the multilink that governs the overall enable state, but that was incorrect, so I've changed it to a local const.

> If the code changed in the future so that the soundManager was created after that emitter fired, we would have no way of knowing, and sound would never be generated. Should we convert this Sim emitter to a Property so it can be checked at any time?

That would be great.  I thought about this during the implementation, but figured it would be pretty obvious if sound broke entirely so the problem would be caught quickly, but if you (as the main caretaker of joist) are up for changing this from an emitter to a property, I agree that it would be a better way to go from the sound manager's perspective.

**Comment by samreid** [comment]
I converted it in the commits, and updated soundManager accordingly.  @jbphet can you please review?

**Comment by jbphet** [comment]
Looks good to me.  I focused more on the `soundManager` changes, but looked over the phet-io and joist changes as well, and they seem reasonable.  Plus, you're one of the experts in both of these areas, so I figure you're well qualified to make them.  I changed a variable name in `soundManager`, but other than that, I think we're good.  Closing.
