### ISSUE TITLE
Create ContinuousSoundPropertyGenerator

### ISSUE THREAD

**Issue by samreid** [phetsims/tambo#76]
See https://github.com/phetsims/wave-interference/issues/436.  The idea is to create a sound generator where pitch varies with a Property value.  I'll create ContinuousSoundPropertyGenerator by generalizing ForceSoundGenerator and create a tambo demo for it.

**Comment by samreid** [comment]
I committed an initial version of ContinousPropertySoundGenerator, as well as sample usage in the tambo demo.  I added 4 sound effects supplied by @Ashton-Morris.  @jbphet can you please review?  If it is in good shape, can Gravity Force Lab: Basics be ported to use it?  Porting Gravity Force Lab: Basics to use it may be a good way to exercise it as part of the review, but let me know if you don't have time for that part and I can give it a try.

**Comment by jbphet** [comment]
I have several comments.  I realize this was ported from Gravity Force Lab Basics, which I created, so it would be fair to assign some of this work back to me if desired, but I thought I'd make the comments and get the review process moving and then we divvy up the work once the changes are agreed upon.

- We should clearly note in the header that this is based on SoundClip and isn't set up to be used with other types of sound-producing audio nodes, such as oscillators.
- I think we should provide a default sound in the options and have the client override instead of requiring it in the constructor.  This will make it easy to drop this in for a quick prototype.
- The `range` value in the constructor should be named something like `propertyRange` and it should be documented that it corresponds to the provided property so that it isn't confused with the playback rate range.
- Should `resetInProgressProperty` should be optional instead of required?  Looking for an opinion here.
- I used `pitchRangeInSemitones` largely because that's how the sound designer and I were discussing it.  We are both pretty comfortable with the term "semitone" and with the MIDI terms used elsewhere in the code.  However, this may well not be familiar terminology for other potential users of this class.  Would it be better to specify it as a multiplier range, e.g. have the option named `playbackRateMultiplierRange` and have it be of type `Range`?  It could have a default value of 0.5 to 2.0, which would be two octaves.
- Related to the previous question, if we change the options to use a multiplier range for the playback rate, `pitchCenterOffset` should also be a multiplier offset value, or maybe not used at all.
- The `trimSilence` option should be set to `true` by default.  It should be set to `false` in the specific GFLB case since it needs very precise operation of the loop.
- There is a TODO item that says, "Some of our sounds are mp3 and have a 'hitch' where no sound plays momentarily.  Would that maybe be fixed if we used *.wav?"  The answer is yes, but first try setting 'trimSilence` to `true`.  That may be enough to make it work in this specific case.  `.wav` files are much bigger than `.mp3` files, so we need to use them very sparingly, and make them as short as possible when we **do** use them.
- There is another TODO item about using `elapsedFadeTime` instead of `remainingFadeTime`.  I generally like to use countdown values for stepped timers because I like the clarity of comparing their values to zero, and because counting down in a situation like this strikes me as more natural.  This may be purely a stylistic preference on my part, so I'm open to discussion if you feel strongly that counting up would be easier for future developers to understand and maintain.

**Comment by samreid** [comment]
This is no longer used in Wave Interference.  If we think there's a good chance it will be used in other sim sonification, it should remain in Tambo. Otherwise, maybe we should consider moving it back to Gravity Force Lab: Basics.  

> I realize this was ported from Gravity Force Lab Basics, which I created, so it would be fair to assign some of this work back to me if desired

Since this was my attempt to generalize the original draft and I no longer have a production-focused simulation that exercises this, I'd be happy for you to take the lead.  But I know time is tight.  Maybe this should be rolled into the code review for GFLB, if that hasn't completed yet?  I'm unsure of the status of that sim.

**Comment by jbphet** [comment]
I implemented my suggestions above or, in some case, decided against them and noted it.  I think that should do it for now, closing.
