### ISSUE TITLE
SoundGenerator outputLevel range

### ISSUE THREAD

**Issue by samreid** [phetsims/tambo#81]
SoundGenerator.setOutputLevel has this documentation:

```js
* @param {number} outputLevel - generally between 0 and 1, but doesn't have to be
```

Can you please elaborate on this?  Are negative values allowed?  If so, why?  When should the value go beyond 1?

I would have expected an assertion for this part that `0 <=outputLevel <=1`.

**Comment by jbphet** [comment]
Good question, I probably should have been more clear.  The value can be greater than 1 in order to boost small input signals.  The value can be negative in order to invert phase.  This is according to the web audio spec, and there is a discussion of it at https://github.com/WebAudio/web-audio-api/issues/506.  I haven't had the need to use values outside of 0 to 1 much, so I don't know how well supported it is between the various browsers.  I'll do a quick test on Chrome and Firefox, since that's easy for me, and update the documentation.

**Comment by samreid** [comment]
Would a value greater than 1 combined with a large input signal risk blowing out anyone's speakers?

**Comment by jbphet** [comment]
Unlikely, but we should take care to avoid doing it.  Most if not all modern computers would just clip if the digital output exceeded 1 dBFS, so it would probably sound nasty, but wouldn't hurt anything.

**Comment by jbphet** [comment]
I just tested large and negative values for gain, and both worked fine.  The test was to set the `initialOutputLevel` for `this.wallContactSoundClip` to 100, then to -1, and test each on both Chrome and Firefox on my Win 10 machine.  This allowed me to hear the contrast between the wall contact sound versus the ceiling-and-floor contact sound.  The value of 100 sounded relatively loud and the end of the sound was much more audible than it was with the previous value of 0.3, but it didn't distort.  This is probably because I have a dynamics compressor in the signal path.

Setting `initialOutputLevel` to -1 seemed to work fine, and sounded the same as having a value of 1.  I assume the phase of the signal is inverted, but it would take some time to verify this and it didn't seem worth the effort to me.  I ended up removing an assert that I previously had in the code that required a positive gain value, since it is conceivable that we would want to invert the phase of a signal someday, say if we wanted to demonstrate cancellation.

@samreid - anything else that we should do here?

**Comment by samreid** [comment]
It seems like a summary of these conclusions should appear in the JSDoc for `SoundGenerator.setOutputLevel`

**Comment by jbphet** [comment]
Summary added.  I just talked about the parameter range, and didn't include anything about the dynamics compressor since it might not be there forever.  Look good?

**Comment by samreid** [comment]
Looks great, thanks!  Closing.
