### ISSUE TITLE
Chrome sound is delayed if sim sits for a time

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/tambo#93]
Found for https://github.com/phetsims/QA/issues/476 but seems like it might impact other sims. Found on Win 10 chrome seems to be just chrome, but may be other platforms. Can be a bit hard to reproduce.
If a sim sits without being touched for ~3 min or more and you go back and immediately try to move a slider that produces sound, it will not do so for a bit of time. This time can vary from starting almost immediately and the pause being hard to notice, to not making sound for almost the length of the slider. After this pause sound seems to be normal.

**Comment by jessegreenberg** [comment]
I just tried to make the problem happen on Windows 10 Chrome. I opened the sim, moved the slider and heard sound, let the sim sit for 5 minutes in the background, then moved the slider again and sound came out immediately.

**Comment by KatieWoe** [comment]
I don't think you can do this if you switch tabs or move the mouse. I was on an entirely different device when this happened.

**Comment by jessegreenberg** [comment]
I see, thanks for the update. I tried the following but was still unable to witness the issue.
- Open sim in Windows 10 Chrome.
- Move slider and hear sound.
- Leave computer for 5 minutes with browser open and active window, without touching mouse.
- Move slider again.

Sound came out immediately.

**Comment by KatieWoe** [comment]
We see it on at least 3 devices, but I'm not too worried about it honestly.

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe that may make it easier to track down. 

> I'm not too worried about it honestly.

I appreciate that, I recommend that we proceed with publications of GFL and Molarity with this issue for now and then decide if any further investigation is necessary beyond that.

**Comment by emily-phet** [comment]
@jessegreenberg - Agreed, let's make sure @jbphet has this on his radar for the future, but proceed towards publication for Molarity for now.

**Comment by jessegreenberg** [comment]
OK thanks @emily-phet - removing my assignment, over to you @jbphet.

**Comment by jbphet** [comment]
I can duplicate this in my Dell XPS Win 10 machine, but the delay is quite small, I would estimate about a second.  I decided to test it against a simple Web Audio demo to see if it was anything that we're doing or something that Chrome or Windows is doing.  I used [this Web Audio oscillator demo](https://webaudioapi.com/samples/oscillator/), and found that the exact some behavior was present.  In other words, if I left the machine alone for ~5 minutes and then came back and pressed the button to turn on the oscillator, there was about a 1 second delay.

This leads me to believe that this problem is not due to anything we're doing in our code, it's instead due to the environment in which the code is running.  Based on this, and on the fact that it's not that significant of an issue (@KatieWoe said above "I'm not too worried about it honestly"), I recommend closing this and not spending any more time on it.

Back to you @KatieWoe - please close if you don't have strong objections to doing so.
