### ISSUE TITLE
Browser thinks user interface sounds are playing

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/tambo#97]
Running http://phettest.colorado.edu/circuit-construction-kit-ac/circuit-construction-kit-ac_en.html?ea&brand=phet
Safari Version 13.0.5 (15608.5.11)
The browser thinks there is audio playing in the sim, even though no audio is actually output. @jbphet thinks this is due to the method of muting user interface sounds (reducing volume to 0).
![out](https://user-images.githubusercontent.com/5090275/75492557-43b1e880-5975-11ea-86bd-7ed16cc4e1ad.gif)

**Comment by jbphet** [comment]
I was doing some other macOS-related work today and thought I'd check to see if the behavior described in this issue was still present in Safari.  I tested on Safari 16.4 and macOS Ventura 13.3 using a recent deployment of the "My Solar System" sim, and the problem _did not occur_.  It looks like Apple may have modified Safari to detect volume levels, which would be great if true.  @oliver-phet - Since you're the one who originally reported this, can you please verify my findings?  If the problem is really gone, we can just close this issue.

**Comment by oliver-phet** [comment]
I just tested and found the same behavior as you, @jbphet!

When sim sound is ENABLED, clicking a check box would play the sound and the audio icon would appear in the browser.
When sim sound is DISABLED, clicking a check box would play no sound and no icon would appear.

Looks like this can be closed!
